# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.26'

    - name: Build
      run: go build -o server main.go

    - name: Debug build output
      run: |
        pwd
        ls -lah

    - name: Start server
      run: |
        ./server > server.log 2>&1 &
        echo $! > server.pid
        sleep 2

    - name: Debug
      run: |
        cat server.log
        ps aux | grep server
        ss -lnt

    - name: Run tests
      run: go test -v ./...

    - name: Stop server
      if: always()
      run: kill $(cat server.pid)
